# Dependencies
#markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Pimp my Keenetic
tagline:          'Pimp my Keenetic'
description:      'Использование роутера ZyXEL за пределами веб-интерфейса, в т.ч. вместе с дополнительным ПО из репозитория <a href="http://entware.net" target="_blank">Entware-ng</a>.'
url:              http://keenetic-gi.ga
baseurl:          /

author:
  name:           'Alexander Ryzhov'
  url:            https://github.com/ryzhovau

paginate:         5

# Custom vars
version:          2.1.0
github:
  repo:           https://github.com/PimpMyKeenetic/PimpMyKeenetic.github.io

# Gems
gems:
  - jekyll-paginate
